@echo off

rem GStreamer 0.10
set GST_MAJOR=0
set GST_MINOR=10

set GST_PLUGINS_BASE_VERSION_MAJOR=%GST_MAJOR%
set GST_PLUGINS_BASE_VERSION_MINOR=%GST_MINOR%
set GST_PLUGINS_BASE_VERSION_MICRO=31
set GST_PLUGINS_BASE_VERSION_NANO=0